[package]
name = "sos"
version = "0.0.0"
authors = ["Jeremy T."]
exclude = ["src/arch/*.asm", "filesystem/*"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
spin = "0.5.2"
bitmap_allocator = { path = "bitmap_allocator" }
