[package]
name = "usb-msc"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
kernel = { path = "../../Core" }
usb-core = { path = "../usb_core" }

storage-scsi = { path = "../storage_scsi" }

